# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:sw=2

[mgr]
cwd = { fg = "cyan" }

hovered         = { fg = "black", bg = "white" }
preview_hovered = { underline = true }

find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

marker_selected = { fg = "lightgreen", bg = "lightgreen" }
marker_copied   = { fg = "lightyellow", bg = "lightyellow" }
marker_cut      = { fg = "lightred", bg = "lightred" }

tab_active   = { fg = "black", bg = "white" }
tab_inactive = { fg = "white", bg = "darkgray" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "gray" }

highlighting = "syntect"

syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

mode_normal = { fg = "black", bg = "blue", bold = true }
mode_select = { fg = "black", bg = "green", bold = true }
mode_unset  = { fg = "black", bg = "red", bold = true }

progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

[select]
border   = { fg = "blue" }
active   = { fg = "magenta" }
inactive = {}

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border   = { fg = "blue" }
active   = { bg = "darkgray" }
inactive = {}

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { underline = true }

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "lightgray" }
desc            = { fg = "magenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer  = { fg = "black", bg = "white" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "cyan" },
	# Videos
	{ mime = "video/*", fg = "yellow" },
	# Audio
	{ mime = "audio/*", fg = "magenta" },
	# Archives
	{ mime = "application/zip",             fg = "magenta" },
	{ mime = "application/gzip",            fg = "magenta" },
	{ mime = "application/x-tar",           fg = "magenta" },
	{ mime = "application/x-bzip",          fg = "magenta" },
	{ mime = "application/x-bzip2",         fg = "magenta" },
	{ mime = "application/x-7z-compressed", fg = "magenta" },
	{ mime = "application/x-rar",           fg = "magenta" },
	{ mime = "application/xz",              fg = "magenta" },
	# Documents
	{ mime = "application/doc",   fg = "green" },
	{ mime = "application/pdf",   fg = "green" },
	{ mime = "application/rtf",   fg = "green" },
	{ mime = "application/vnd.*", fg = "green" },
	# Empty files
	{ mime = "inode/x-empty", fg = "red" },
	# Special files
	{ name = "*", is = "orphan", bg = "red" },
	{ name = "*", is = "exec",   fg = "green" },
	# Default
	{ name = "*/", fg = "blue" }
]

[git]
modified  = { fg = "orange" }
added     = { fg = "green" }
untracked = { fg = "lightgray" }
ignored   = { fg = "darkgray" }
deleted   = { fg = "red" }
